### ISSUE TITLE
AKS Learn feedback: code snippet does not work

### ISSUE THREAD

**Issue by singhr6** [MicrosoftDocs/azure-aks-docs#129]
### Type of issue

Code doesn't work

### Feedback

Hi , below code mentioned under Create an internal NGINX ingress controller with a private IP address of https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration?tabs=azurecli does not work.  This yaml gives error : error: unable to recognize 'nginx-internal-controller.yaml': no matches for kind 'NginxIngressController' in version 'approuting.kubernetes.azure.com/v1alpha1'

```
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-internal
spec:
  ingressClassName: nginx-internal
  controllerNamePrefix: nginx-internal
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

```

### Page URL

https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration?tabs=azurecli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/app-routing-nginx-configuration.md

### Author

@schaffererin

### Document Id

df461a68-1b34-e770-41b1-cc1713fdb2dc
