### ISSUE TITLE
Add scrape job for node metrics to BYO Prometheus example

### ISSUE THREAD

**Issue by jowhitehead** [MicrosoftDocs/azure-aks-docs#148]
### Type of issue

Missing information

### Feedback

In our documentation for Container Networking Observability, we have examples for enabling Azure-managed Grafana/Prometheus and for BYO Grafana/Prometheus. In the BYO option, we have a scrape job for the Prometheus server to report pod metrics: 
https://learn.microsoft.com/en-us/azure/aks/container-network-observability-how-to?tabs=non-cilium#visualization-using-byo-grafana

However, there isn't a job for adding the node-level metrics which are reported by the retina daemonset pods on port 10093.
Should we add a scrape job for those metrics too? 

```
- job_name: networkobservability-retina
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_k8s_app]
      regex: kube-system;(retina|cilium)
      action: keep
    - source_labels: [__address__]
      action: replace
      regex: ([^:]+)(?::\d+)?
      replacement: $1:10093
      target_label: __address__
    - source_labels: [__meta_kubernetes_pod_node_name]
      target_label: instance
      action: replace
```

### Page URL

https://learn.microsoft.com/en-us/azure/aks/container-network-observability-how-to?tabs=non-cilium#enable-advanced-container-networking-services-on-an-existing-cluster

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/container-network-observability-how-to.md

### Author

@Khushbu-Parekh

### Document Id

d13222b2-4f67-0cf6-25df-42a6c9cc1195
