### ISSUE TITLE
AKS Learn feedback: Load Balancer URL giving 404 Not Found

### ISSUE THREAD

**Issue by nitin27verma** [MicrosoftDocs/azure-aks-docs#158]
Removed details because of privacy.

**Comment by nitin27verma** [comment]
`kubectl create namespace aks-hello`
# Listed below are the deployed resources (ns, deploy, svc and ingress)
```
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-internal
spec:
  ingressClassName: nginx-internal
  controllerNamePrefix: nginx-internal
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
	service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "sb-aks-userpool"
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
	  nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: aks-helloworld
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 8080
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: aks-helloworld
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld
  namespace: aks-hello
spec:
  ingressClassName: nginx-internal
  rules:
  - host: aks-helloworld.aks.example.com
    http:
      paths:
      - backend:
          service:
            name: aks-helloworld
            port:
              number: 80
        path: /
        pathType: Prefix
```
