### ISSUE TITLE
AKS Learn feedback: Karpenter/NAP API update and spec changes for NodePool

### ISSUE THREAD

**Issue by ehrnst** [MicrosoftDocs/azure-aks-docs#233]
### Type of issue

Code doesn't work

### Feedback

I am not sure if this is an AKS automatic thing, or a NAP thing. But after playing around with automatic for a couple of months I noticed today that there's an updated API to the nodepool resource. Specifically my newly created automatic cluster is using api version v1. Which requires changes to the properties `consolidationPolicy` , `consolidateAfter`. The `kind` of nodeclass and the `group`

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: <name>
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10s
  template:
    spec:
      nodeClassRef:
        name: default
        kind: aksnodeclass
        group: karpenter.azure.com
      # Requirements that constrain the parameters of provisioned nodes.
      # These requirements are combined with pod.spec.affinity.nodeAffinity rules.
      # Operators { In, NotIn, Exists, DoesNotExist, Gt, and Lt } are supported.
      # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.azure.com/sku-family
        operator: In
        values:
        - D
```

### Page URL

https://learn.microsoft.com/en-us/azure/aks/node-autoprovision?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/node-autoprovision.md

### Author

@schaffererin

### Document Id

d269da23-8613-c13b-6fb8-601b251fd96f

### Platform Id

c2d3fe48-8d16-c42c-9c42-10c07a1611fd
